### ISSUE TITLE
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by mackoj** [bitrise-io/trace-cocoa-sdk#81]
### Your environment:

  * Xcode version: 13b4
  * Trace SDK version: 1.7.36
  * Installation method: `SPM`
  * iOS Version: 15
  * Swift Version (Optional): 5.5

#### Steps to reproduce:

Build an app that depend on Trace with Xcode beta 3 and 4 to enable this issue.
```'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.```
In a few place in the code base.

Please consider adding this when needed.

`@available(iOSApplicationExtension, unavailable)`

Thanks,

**Comment by shams-ahmed** [comment]
@mackoj Thanks for the feedback, we're looking at adding support for Xcode 13 very soon.

**Comment by shams-ahmed** [comment]
@mackoj Please set `Require Only App-Extension-Safe API `to NO under your application build setting. See screenshot for example. This should resolve your issue and allow you to build your project. At this point in time Trace will not support application extension. 

More information from [Apple doc](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html).

<img width="982" alt="Screenshot 2021-08-10 at 5 27 13 " src="https://user-images.githubusercontent.com/2887472/128896878-615f7366-b623-4821-b1a4-b755f45e1e52.png">

**Comment by shams-ahmed** [comment]
Closing issue since it has been fixed in the latest version of Xcode 13 beta. Ongoing changes are tracked #84 issue.
