### ISSUE TITLE
Crash on iOS 12.x

### ISSUE THREAD

**Issue by mtagliafico** [bitrise-io/trace-cocoa-sdk#87]
### Your environment:

  * Xcode version: 12.5.1
  * Trace SDK version: 1.2.4
  * Installation method: `Trace Step`
  * iOS Version: 12.1.0 (16B92)

#### Steps to reproduce:

What happened? How can we reproduce this problem?
On iOS 12.x Firebase alerts me about a recurring crash. Here's the stack-trace:
<img width="934" alt="Screenshot 2021-08-31 at 08 33 04" src="https://user-images.githubusercontent.com/67682136/131454039-1729d198-8203-462f-8ad4-916f703106a9.png">

Are you aware about this issue?

**Comment by shams-ahmed** [comment]
@mtagliafico Thanks for reporting the issue.
Yes, we are aware of the specific issue. I believe this was resolved some time ago. I can see you're using a very old version (nearly 1 year) of the SDK, is it possible to update to v1.7.37.

https://github.com/bitrise-io/trace-cocoa-sdk/releases/tag/1.7.37

A simple redeploy should fetch the latest version if you're using a trace step.

Let us know if you still experience the same issue.

**Comment by mtagliafico** [comment]
@shams-ahmed I'm sorry but I reported the step's version instead the of version of the SDK.
The SDK version is 1.7.37:

```
+------------------------------------------------------------------------------+

| (5) add-trace-sdk@1                                                          |
+------------------------------------------------------------------------------+
| id: add-trace-sdk                                                            |
| version: 1.2.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2021-08-30T16:33:12Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Installing step dependencies
[REDACTED]
Installing gem: down
true
Found gem: json
true
Found gem: plist
true
Found gem: xcodeproj
true
Found gem: rubyzip
Installed step dependencies
Checking Xcode version
Xcode version: Xcode 12.5.1
Running Trace step
Will start download for version: latest
Downloaded Trace library
Starting step with path: **XXX.**xcworkspace, scheme: 0. **XXX** - SYS, trace version: latest
Moving downloaded file to: ./libTrace.a.zip
File location path is malformed: ./libTrace.a.zip
Make sure path is a relative path with the full root
Unzipping Trace SDK package
Unzipping: ./libTrace.a
Trace SDK Version unzipped: 1.7.37
```

**Comment by shams-ahmed** [comment]
@mtagliafico Please try using v1.7.39 just been deployed or doing a redeploy if your using the Trace step
